services:
  postgresql:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pms
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
